apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-api
  labels:
    app: my-api
spec:
  selector:
    matchLabels:
      app: my-api
  replicas: 2
  template:
    metadata:
      labels: # labels to select/identify the deployment
          app: my-api 
    spec:     # pod spec                  
      containers: 
      - name: my-api
        image: apiv1
        imagePullPolicy: Never
        ports:
        - containerPort: 5050
       

---
apiVersion: v1
kind: Service
metadata:
  name: my-api
spec:
  type: NodePort
  selector:
    app: my-api
  ports:
  - port: 80
    targetPort: 5050
